version: '3'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ../:/var/www
        ports:
            - "8810:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ../:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
     #MySQL Service
    database:
      image: mysql:5.7
      container_name: mysqldatabase
      restart: unless-stopped
      tty: true
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: laraveldb
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravelpassworddb
        MYSQL_ROOT_PASSWORD: rootpasswordmysql
